name: export-and-commit-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'URL of the source environment to export the solution from'
        required: true
        default: 'https://orgc1146975.crm3.dynamics.com/'
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: 'FASB Invoice Tracking'
      #totp_secret:
      #  description: 'time based otp secret for poc deploys (use client-secret) '
      #  required: true
        
      
env:
#edit your values here
  ENVIRONMENT_URL: ${{ github.event.inputs.solution_name }}
  #TOTP: ${{ github.event.inputs.totp_secret }}

permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
                
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}

        #just for Demo purposes
        #totp: ${{env.TOTP}}
        user-name: ${{ secrets.USER_NAME }}
        password-secret: ${{ secrets.USER_PASSWORD }}

        #Prefered Auth Method
        #app-id: ${{secrets.CLIENT_ID}}
        #client-secret: ${{ secrets.PowerPlatformSPN }}
        #tenant-id: ${{secrets.TENANT_ID}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}

        #just for Demo purposes
        #totp: ${{env.TOTP}}
        user-name: ${{ secrets.USER_NAME }}
        password-secret: ${{ secrets.USER_PASSWORD }}
        
        #Prefered Auth Method
        #app-id: ${{secrets.CLIENT_ID}}
        #client-secret: ${{ secrets.PowerPlatformSPN }}
        #tenant-id: ${{secrets.TENANT_ID}}
        
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        overwrite: true
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        solution-folder: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: export-managed-solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
            environment-url: ${{env.ENVIRONMENT_URL}}
            
            #just for Demo purposes
            
            #totp: ${{env.TOTP}}
            user-name: ${{ secrets.USER_NAME }}
            password-secret: ${{ secrets.USER_PASSWORD }}

            #Prefered Auth Method
            #app-id: ${{secrets.CLIENT_ID}}
            #client-secret: ${{ secrets.PowerPlatformSPN }}
            #tenant-id: ${{secrets.TENANT_ID}}
            
            solution-name: ${{ github.event.inputs.solution_name }}
            solution-output-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
            overwrite: true
            managed: true
    
    
    - name: Git Fetch and Commit 
      run: |
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment" --allow-empty
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
